### PR TITLE
feat: update vault and vault operator to latest versions

### PR DESCRIPTION
**Pull request by ccojocar**
requires https://github.com/jenkins-x/jx/pull/5649

fixes https://github.com/jenkins-x/jx/issues/5113

### CODE REVIEW

**Comment by abayer** [comment]
So this won't pass 'til https://github.com/jenkins-x/jx/pull/5649 is in, or am I interpreting this wrongly? =)

**Comment by ccojocar** [comment]
It will pass but with an older version of the vault-operator. It would be better to wait until the jx PR gets merged to really test with latest operator version.

**Pull request merged**
