### PR TITLE
feat: update jx dependencies on full release of jx

### PR DESCRIPTION
**Pull request by cagiti**
Signed-off-by: Cai Cooper <caicooper82@gmail.com>

### CODE REVIEW

**Comment by rawlingsj** [comment]
@cagiti @abayer I'm thinking we try this and we can followup in the morning.

/hold cancel

**Comment by rawlingsj** [comment]
most looked good - not sure if this is related but the versions master build failed with the below, so looks like it's missing some env vars.
```
Showing logs for build jenkins-x-jenkins-x-versions-ma-kqfmr-64 stage changelog and container step-update-jx-bot
error: unable to create pull request: failed to fork and pull [https://github.com/jenkins-x/homebrew-**.git]: git output: *** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'root@jenkins-x-jenkins-x-versions-ma-kqfmr-64-changelog-znjmb-pod-2c.(none)'): failed to run 'git commit -a -m initial commit --allow-empty' command in directory '/tmp/create-pr534769289', output: '*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

```

**Comment by cagiti** [comment]
Ah damn, I did forget to copy over the env vars into the pipeline :doh:

**Comment by cagiti** [comment]
Does it possibly need https://github.com/jenkins-x/jenkins-x-versions/pull/525

**Pull request merged**
