### PR TITLE
feat: increase cert manager version

### PR DESCRIPTION
**Pull request by dgozalo**
Increasing cert manager version to 0.11 to make it work correctly with EKS.

### CODE REVIEW

**Comment by grischa** [comment]
Great! I'm deploying on EKS at the moment and needed this
Btw, as mentioned here: https://github.com/jenkins-x/dex/pull/24 the JX managed dex chart is currently incompatible with cm 0.11

**Comment by dgozalo** [comment]
Waiting until jenkins-x/jx#6327 merges and we generate a builder to close this one.

**Pull request closed without merging**
